### ISSUE TITLE
功能需求: 重用小程序平台的意见反馈功能

### ISSUE THREAD

**Issue by NeverMin** [stevekeol/DonationChannel-2.0#9]
重用小程序平台的意见反馈功能, 收集用户意见作为后续进版或增加功能之用.

![image](https://user-images.githubusercontent.com/2797432/76149902-8e530380-60df-11ea-8d81-cdfa47be0b3a.png)

小程序摆放位置:
![image](https://user-images.githubusercontent.com/2797432/76149927-cce8be00-60df-11ea-8fed-292dfc3b055d.png)

**Comment by stevekeol** [comment]
OK, nice
